site_name: Land Registration Blockchain For Sri Lanka
nav:
    - Home: index.md
    - User Manaul: user_manual.md
    - System Manaul: system_manual.md
    - About: about.md

extra_css: [css/extra.css]