site_name: LRBSL
theme: readthedocs

nav:
    - Introduction:
        - '01-Introduction'
    - User Manual:
        - '02-User-manual'
    - System Manaul:
        - '03-System-manual'
    - Support:
        - '04-Support'

extra_css: [css/extra.css]